### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by AaronHForgeFlow** [ForgeFlow/stock-rma#125]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [x] rma - By @AaronHForgeFlow - #127
- [x] rma_account - By @AaronHForgeFlow - #128 
- [ ] rma_analytic 
- [ ] rma_operating_unit
- [ ] rma_purchase - By @Chanakya-SerpentCS - #143
- [ ] rma_purchase_analytic
- [ ] rma_quality_control_issue
- [ ] rma_repair
- [x] rma_sale - By @AaronHForgeFlow - https://github.com/ForgeFlow/stock-rma/pull/129
- [ ] rma_sale_analytic
- [ ] account_move_line_rma_order_line

**Comment by max3903** [comment]
@AaronHForgeFlow We will migrate rma_purchase by the end of the week.

**Comment by bodedra** [comment]
rma_purchase - https://github.com/ForgeFlow/stock-rma/pull/143
