### ISSUE TITLE
Migration to 14.0

### ISSUE THREAD

**Issue by AaronHForgeFlow** [ForgeFlow/stock-rma#151]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

# Modules to migrate

- [x] rma - By @MateuGForgeFlow  - #146 
- [x] rma_account - By @MateuGForgeFlow  - #147 
- [ ] rma_analytic 
- [ ] rma_operating_unit
- [x] rma_purchase - By @MateuGForgeFlow  - #153 
- [ ] rma_purchase_analytic
- [ ] rma_quality_control_issue
- [x] rma_repair - By @MateuGForgeFlow  - #154 
- [x] rma_sale - By @MateuGForgeFlow  - #148 
- [ ] rma_sale_analytic
- [x] account_move_line_rma_order_line
