### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by max3903** [ForgeFlow/stock-rma#29]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] rma - by @bodedra - in #28 
- [x] rma_account - by @bodedra - in #30
- [ ] rma_account_analytic
- [ ] rma_analytic
- [ ] rma_operating_unit
- [x] rma_purchase - by @bodedra - in #31
- [ ] rma_purchase_analytic
- [ ] rma_quality_control_issue
- [ ] rma_repair
- [x] rma_sale - by @aheficent https://github.com/Eficent/stock-rma/pull/42
- [ ] rma_sale_analytic
- [x] account_move_line_rma_order_line - by @aheficent #46
