### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by AaronHForgeFlow** [ForgeFlow/stock-rma#54]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [x] rma - @ageficent - in #52 
- [x] rma_account - @ageficent - in #53  
- ~~[ ] rma_account_analytic~~ - merged in rma_analytic
- [ ] rma_analytic - By @aheficent - in #110 
- [ ] rma_operating_unit - @bjeficent  - in #63 
- [x] rma_purchase - By @murtuzasaleh - in https://github.com/Eficent/stock-rma/pull/69
- [ ] rma_purchase_analytic
- [ ] rma_quality_control_issue
- [x] rma_repair - By @grindtildeath - in #65 
- [x] rma_sale - @grindtildeath  - in #66 
- [ ] rma_sale_analytic
- [x] account_move_line_rma_order_line By @aheficent - #95

**Comment by max3903** [comment]
Hello @aheficent,

@murtuzasaleh would like to migrate rma_purchase. Are you planning to make any changes while migrating? Or will you accept the module if he migrates it as is?

**Comment by AaronHForgeFlow** [comment]
Hi @max3903 @murtuzasaleh Thank you for the proposal. Yes, you can port it as it is. Regards.
